openapi: 3.0.0
info:
  title: Students managing API
  version: 2.0.0
tags:
  - name: v1
    description: Version 1.0.0 de HEI-managing-api
  - name: v2
    description: Version 2.0.0 de HEI-managing-api
servers:
  - url: https://STD22064.com
paths:
  '/students/{id}':
    get:
      tags: 
        - v1
      summary: Get student informations by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          example: 
            "id": 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                "id": 1
                "name": "Josia"
                "birthdate": "2001-06-10"
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                message: An error occurred
    put:
      tags:
        - v2
      summary: Update student by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          example: 
            "id": 3
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                birthdate:
                  type: string
              required:
                - name
                - birthdate
            example: 
              "name": Rasta
              "birthdate": "2003-05-08"
      responses:
        '200':
          description: Student details successfully updated
          content: 
            application/json: 
              example: 
                "id": 3
                "name": Rasta
                "birthdate": "2003-05-08"
        '500': 
          description: Internal server error
          content:
            application/json:
              example:
                message: An error occurred
          
    delete: 
      tags: 
        - v2
      summary: Supprimer un étudiant par ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          example: 
            "id": 3
      responses:
        '200':
          description: Student deleted succesfully
          content: 
            application/json: 
              example: 
                "id": 3
                "name": Rasta
                "birthdate": "2003-05-08"
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                message: An error occurred
  /students:
    post:
      tags : 
        - v1
      summary: Add a new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                birthdate:
                  type: string
              required:
                - id
                - name
                - birthdate
            example:
              id: 2
              name: "Kioto"
              birthdate: "2001-01-06"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: Student added successfully
                "name": "Kioto"
                "birthdate": "2001-01-06"
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                message: An error occurred
  /teachers:
    post:
      tags:
        - v2
      summary: Add a new teacher
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                lastname:
                  type: string
                courses:
                  type: array
                  items:
                    type: object
                    properties:
                      course-name:
                        type: string
                      course-code: 
                        type: string
                      course-duration:
                        type: string
              required:
                - firstname
                - lastname
                - courses
            example: 
              "firstname": Ryan
              "lastname": Raveloson
              "courses":
                - course-name: Interface de Prigrammation
                  course-code: API
                  course-duration: 20 heures
                - course-name: Mathématique appliquée
                  course-code: THEORIE2
                  course-duration: 25 heures
      responses: 
        '200': 
          description: Teacher successfully added
          content:
            application/json:
              example:
                "id": 5
                "firstname": Ryan
                "lastname": Raveloson
                "courses":
                  - course-name: Interface de Prigrammation
                    course-code: API
                    course-duration: 20 heures
                  - course-name: Mathématique appliquée
                    course-code: THEORIE2
                    course-duration: 25 heures
        '500': 
          description: Internal server error
          content:
            application/json:
              example:
                message: An error occurred
                  
    get:
      tags:
        - v2
      summary: Retrieve the list of teachers
      responses:
        '200':
          description: Teachers list successfully retrieved
            
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                message: An error occurred
          
  '/teachers/{id}':
    get:
      tags:
        - v2
      summary: Retrieve teacher details by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          example: 
            "id": 4
      responses:
        '200':
          description: Teacher informations successfully retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstname:
                    type: string
                  lastname:
                    type: string
                  courses:
                    type: array
                    items:
                      type: object
                      properties:
                        course-name:
                          type: string
                        course-code: 
                          type: string
                        course-duration:
                          type: string
              example:
                "id": 4
                "firstname": Tokimahery
                "lastname": Ramarozaka
                "courses":
                  - course-name: Programmmation
                    course-code: PROG1
                    course-duration: 30 heures
                  - course-name: Developpement WEB
                    course-code: WEB1
                    course-duration: 28 heures
 
