openapi: 3.0.0
info:
  title: Students managing API
  version: 2.0.0
tags:
  - name: v1
    description: Version 1.0.0 de HEI-managing-api
  - name: v2
    description: Version 2.0.0 de HEI-managing-api
servers:
  - url: https://STD22064.com
paths:
  /v1/students:
    get:
      summary: Get student informations
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                "id": 1
                "name": "Josia"
                "birthdate": "2001-06-10"
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                message: An error occurred

    post:
      summary: Add a new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                birthdate:
                  type: string
              required:
                - id
                - name
                - birthdate
            example:
              id: 2
              name: "Kioto"
              birthdate: "2001-01-06"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: Student added successfully
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                message: An error occurred while adding the student
  /v2/students:
    get:
      summary: Get studentsssssss informations
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                "id": 1
                "name": "Josia"
                "birthdate": "2001-06-10"
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                message: An error occurred

    post:
      summary: Add a new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                birthdate:
                  type: string
              required:
                - id
                - name
                - birthdate
            example:
              id: 2
              name: "Kioto"
              birthdate: "2001-01-06"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: Student added successfully
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                message: An error occurred while adding the student

